### PR TITLE
Additional classes to give more control

### PR DESCRIPTION
**Pull request by majurgens**
I've added more classes to give more control over which modules can be shown and when. The motivation for this was that I wanted to use the facial recognition module in combination with a carousel module. This needed some additional classes so that I could make the facial recognition module not touch the carousel controlled modules. When facial recognition and carousel tried to show/hide the same modules, it looked a bit ugly (all carousel modules were shown at the same time) until the second cycle of the carousel came around. The new 'always' class means that at least now you can have a class that is always shown ie not touched by facial recognition.

I also found that having multiple concurrent logged in users could make a mess of the modules shown/hidden. For now I have made a configuration setting that defaults to limiting to a single logged in user at a time. There is more work for me to do in this area to properly support multiple concurrent logins. 

I've also updated the documentation with all these changes

I have changed the welcome message to support a different message when the user is known vs unknown and modified all translations to also support this.

### CODE REVIEW

**Comment by nischi** [comment]
I really like your work. Thanks a lot for your effort.

I'm sorry, the previous PR did a conflict on yours. can you please fix it shortly? Shouldn't be a big deal, i hope. THANKS.

**Comment by nischi** [comment]
Should solve #36 and #38

**Comment by majurgens** [comment]
I'm a bit new to using github but I think I've resolved it properly. My code effectively overwrites and replaces the other conflicting code.

**Comment by nischi** [comment]
nice, thanks for the fast commit

**Pull request merged**
